/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package serviciocoches.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Coche service. Represents a row in the &quot;FOO_Coche&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link serviciocoches.model.impl.CocheModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link serviciocoches.model.impl.CocheImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Coche
 * @see serviciocoches.model.impl.CocheImpl
 * @see serviciocoches.model.impl.CocheModelImpl
 * @generated
 */
@ProviderType
public interface CocheModel extends BaseModel<Coche> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a coche model instance should use the {@link Coche} interface instead.
	 */

	/**
	 * Returns the primary key of this coche.
	 *
	 * @return the primary key of this coche
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this coche.
	 *
	 * @param primaryKey the primary key of this coche
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the matricula of this coche.
	 *
	 * @return the matricula of this coche
	 */
	@AutoEscape
	public String getMatricula();

	/**
	 * Sets the matricula of this coche.
	 *
	 * @param Matricula the matricula of this coche
	 */
	public void setMatricula(String Matricula);

	/**
	 * Returns the marca of this coche.
	 *
	 * @return the marca of this coche
	 */
	@AutoEscape
	public String getMarca();

	/**
	 * Sets the marca of this coche.
	 *
	 * @param Marca the marca of this coche
	 */
	public void setMarca(String Marca);

	/**
	 * Returns the modelo of this coche.
	 *
	 * @return the modelo of this coche
	 */
	@AutoEscape
	public String getModelo();

	/**
	 * Sets the modelo of this coche.
	 *
	 * @param Modelo the modelo of this coche
	 */
	public void setModelo(String Modelo);

	/**
	 * Returns the precio of this coche.
	 *
	 * @return the precio of this coche
	 */
	public double getPrecio();

	/**
	 * Sets the precio of this coche.
	 *
	 * @param Precio the precio of this coche
	 */
	public void setPrecio(double Precio);

	/**
	 * Returns the precio con iva of this coche.
	 *
	 * @return the precio con iva of this coche
	 */
	public double getPrecioConIva();

	/**
	 * Sets the precio con iva of this coche.
	 *
	 * @param PrecioConIva the precio con iva of this coche
	 */
	public void setPrecioConIva(double PrecioConIva);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(serviciocoches.model.Coche coche);

	@Override
	public int hashCode();

	@Override
	public CacheModel<serviciocoches.model.Coche> toCacheModel();

	@Override
	public serviciocoches.model.Coche toEscapedModel();

	@Override
	public serviciocoches.model.Coche toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}